### ISSUE TITLE
А как же композит?

### ISSUE THREAD

**Issue by olegpro** [denx-b/bitrix-blank#1]
if ($APPLICATION->get_cookie('G_FONTS') == '1') в header.php шаблона.

**Comment by denx-b** [comment]
Да, точно, результат кешируется. Тут можно конечно извратиться через обработку буфера, [по принципу](https://github.com/denx-b/bitrix-css-to-head/blob/master/test.php), либо убрать вовсе. Но думаю попробовать всё-таки стоит.

**Comment by denx-b** [comment]
От этого отказался вообще.
